version: '3.8'
services:
  angular-docker-dev:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
